#!/bin/bash

# Get current status of a git repository
function parse_git_status {
  status=$(git status 2> /dev/null)
  local bits=""

  if [[ "$status" == *"Your branch is ahead"* ]]; then
    bits+=">"
  elif [[ "$status" == *"Your branch is behind"* ]]; then
    bits+="<"
  fi
  if [[ "$status" == *"Changes to be committed"* ]]; then
    bits+="="
  fi
  if [[ "$status" == *"Changes not staged for commit"* ]]; then
    bits+="~"
  fi
  if [[ "$status" == *"Untracked files"* ]]; then
    bits+="?"
  fi
  if [[ "$status" == *"Unmerged paths"* ]]; then
    bits+="!"
  fi

  if [[ -n "$bits" ]]; then
    echo " $bits"
  else
    echo ""
  fi
}

# Get branch and status of a git repository
function parse_git() {
  br=$(git branch --show-current 2> /dev/null)
  st=""

  if [[ -n "$br" ]]; then
    if [[ $1 == "status" ]]; then
      st=$(parse_git_status)
    fi
    echo " [$br$st]"
  else
    echo ""
  fi
}
