theme = "onedark"

[editor]
auto-info = true
auto-pairs = false
bufferline = "always"
color-modes = true
line-number = "relative"
mouse = false

[editor.statusline]
left = ["mode", "file-name", "file-type", "version-control"]
right = ["spinner", "diagnostics", "primary-selection-length", "selections", "position", "position-percentage", "total-line-numbers"]

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[keys.normal."\\"]
u = ":update"
q = ":quit-all"
Q = ":quit-all!"
w = ":buffer-close"
W = ":buffer-close!"

[keys.insert.j]
j = "normal_mode"
