#!/bin/bash

# List files after changing directory
function cdls {
  local count=$(ls -1 | wc -l)

  if [[ $count -gt 100 ]]; then
    echo "Too many files to display ($count)"
    return
  fi

  ls -F --color=auto --group-directories-first
}
