#!/usr/bin/env zsh

# List files after changing directory
function cdls {
  local count=$(ls -1 | wc -l)

  if (( count > 100 )); then
    print "Too many files to display ($count)"
    return
  fi

  ls -F --color=auto --group-directories-first
}
