#!/usr/bin/env zsh

# Go to the n-th parent folder
function up {
  local n=${1:-1}

  if (( n <= 0 )) || (( $# > 1 )); then
    print "Usage: up [n > 0]" >&2
    return 1
  fi

  cd "$(printf '../%.0s' {1..$n})" || return
}
