#!/bin/bash

# Go to the n-th parent folder
function up {
  if [[ $# -eq 0 ]]; then
    cd "../"
    return
  fi

  if [[ $# -gt 1 ]] || [[ $1 -le 0 ]]; then
    echo "Usage: up [n > 0]"
  fi

  local dir=""
  for _ in $(seq 1 "$1"); do
    dir+="../"
  done

  cd "$dir" || return
}
