[General]
AllowGrabBaseKeypad=true
AllowGrabBaseSpecial=false
AllowGrabLocks=false
AllowGrabMiscKeypad=true
AllowGrabMiscSpecial=true
MultipleActionsBehaviour=first
WindowSize=@Size(800 400)

[Alt%2BF1.1]
Comment=Show/hide main menu
Enabled=false
path=/panel/fancymenu/show_hide

[Control%2BAlt%2BDelete.2]
Comment=Task Manager
Enabled=true
Exec=qps

[Control%2BAlt%2BT.3]
Comment=Terminal
Enabled=true
Exec=x-terminal-emulator

[Control%2BF10.4]
Comment=Switch to desktop 10
Enabled=false
path=/panel/desktopswitch/desktop_10

[Control%2BF11.5]
Comment=Switch to desktop 11
Enabled=false
path=/panel/desktopswitch/desktop_11

[Control%2BF12.6]
Comment=Switch to desktop 12
Enabled=false
path=/panel/desktopswitch/desktop_12

[Control%2BF4.7]
Comment=Switch to desktop 4
Enabled=false
path=/panel/desktopswitch/desktop_4

[Control%2BF5.8]
Comment=Switch to desktop 5
Enabled=false
path=/panel/desktopswitch/desktop_5

[Control%2BF6.9]
Comment=Switch to desktop 6
Enabled=false
path=/panel/desktopswitch/desktop_6

[Control%2BF7.10]
Comment=Switch to desktop 7
Enabled=false
path=/panel/desktopswitch/desktop_7

[Control%2BF8.11]
Comment=Switch to desktop 8
Enabled=false
path=/panel/desktopswitch/desktop_8

[Control%2BF9.12]
Comment=Switch to desktop 9
Enabled=false
path=/panel/desktopswitch/desktop_9

[Meta%2B0.13]
Comment=Activate task 10
Enabled=false
path=/panel/taskbar/task_10

[Meta%2B1.14]
Comment=Switch to desktop 1
Enabled=true
path=/panel/desktopswitch/desktop_1

[Meta%2B1.15]
Comment=Activate task 1
Enabled=false
path=/panel/taskbar/task_1

[Meta%2B2.16]
Comment=Activate task 2
Enabled=false
path=/panel/taskbar/task_2

[Meta%2B2.17]
Comment=Switch to desktop 2
Enabled=true
path=/panel/desktopswitch/desktop_2

[Meta%2B3.18]
Comment=Activate task 3
Enabled=false
path=/panel/taskbar/task_3

[Meta%2B3.19]
Comment=Switch to desktop 3
Enabled=true
path=/panel/desktopswitch/desktop_3

[Meta%2B4.20]
Comment=Activate task 4
Enabled=false
path=/panel/taskbar/task_4

[Meta%2B5.21]
Comment=Activate task 5
Enabled=false
path=/panel/taskbar/task_5

[Meta%2B6.22]
Comment=Activate task 6
Enabled=false
path=/panel/taskbar/task_6

[Meta%2B7.23]
Comment=Activate task 7
Enabled=false
path=/panel/taskbar/task_7

[Meta%2B8.24]
Comment=Activate task 8
Enabled=false
path=/panel/taskbar/task_8

[Meta%2B9.25]
Comment=Activate task 9
Enabled=false
path=/panel/taskbar/task_9

[Meta%2BD.26]
Comment=Show desktop
Enabled=true
path=/panel/showdesktop/show_hide

[Meta%2BE.27]
Comment=File Manager
Enabled=true
Exec=pcmanfm-qt

[Meta%2BL.28]
Comment=Lockscreen
Enabled=true
Exec=xdg-screensaver, lock

[Meta%2BR.29]
Comment=Show/hide runner dialog
Enabled=false
path=/runner/show_hide_dialog

[Meta%2BR.30]
Comment=Application Launcher
Enabled=true
Exec=rofi, -show, drun

[Meta%2BT.31]
Comment=Terminal
Enabled=true
Exec=x-terminal-emulator

[Meta%2BW.32]
Comment=Web Browser
Enabled=true
Exec=x-www-browser

[Print.33]
Comment=Screenshot
Enabled=true
Exec=screengrab, -f

[Shift%2BPrint.34]
Comment=Screenshot (region)
Enabled=true
Exec=screengrab, -r

[XF86AudioLowerVolume.35]
Comment=Decrease sound volume
Enabled=true
path=/panel/volume/down

[XF86AudioMute.36]
Comment=Mute/unmute sound volume
Enabled=true
path=/panel/volume/mute

[XF86AudioRaiseVolume.37]
Comment=Increase sound volume
Enabled=true
path=/panel/volume/up

[XF86Eject.38]
Comment=Eject removable media
Enabled=false
path=/panel/mount/eject

[XF86MonBrightnessDown.39]
Comment=☀ ↓
Enabled=true
Exec=lxqt-config-brightness, -d

[XF86MonBrightnessUp.40]
Comment=☀ ↑
Enabled=true
Exec=lxqt-config-brightness, -i

[XF86PowerOff.41]
Comment=Power off key action
Enabled=false
path=/powermanager/keypoweroff

[XF86Sleep.42]
Comment=Hibernate key action
Enabled=false
path=/powermanager/keyhibernate

[XF86Suspend.43]
Comment=Suspend key action
Enabled=false
path=/powermanager/keysuspend
