#!/bin/bash

function prompt_personal_precmd {
  vcs_info
  prompt_git=""
  if [[ -n $vcs_info_msg_0_ ]]; then
    prompt_git=" · %F{yellow}${vcs_info_msg_0_}%f"
  fi
}

function prompt_personal_setup {
  prompt_opts=(cr sp percent subst)
  add-zsh-hook precmd prompt_personal_precmd
  PS1='%F{green}%n@%M%f · %B%F{blue}%~%f%b${prompt_git}%(?.. · %B%F{red}%?%f%b)${prompt_newline}%F{magenta}%#%f '
  RPS1=' %F{cyan}%*%f'
  PS2='%F{magenta}%_ %#%f '
}

prompt_personal_setup "@"
