vim.o.termguicolors = true
vim.o.background = 'dark'
vim.g.colors_name = 'onedark'

local p = {
  black       = '#181a1f',
  bg0         = '#282c34',
  bg1         = '#31353f',
  bg2         = '#393f4a',
  bg3         = '#3b3f4c',
  bg_d        = '#21252b',
  fg          = '#abb2bf',
  blue        = '#61afef',
  purple      = '#c678dd',
  green       = '#98c379',
  orange      = '#d19a66',
  yellow      = '#e5c07b',
  cyan        = '#56b6c2',
  red         = '#e86671',
  bg_blue     = '#73b8f1',
  bg_yellow   = '#ebd09c',
  grey        = '#5c6370',
  light_grey  = '#848b98',
  dark_cyan   = '#2b6f77',
  dark_red    = '#993939',
  dark_yellow = '#93691d',
  dark_purple = '#8a3fa0',
  diff_add    = '#31392b',
  diff_delete = '#382b2c',
  diff_change = '#1c3448',
  diff_text   = '#2c5372',
}

local groups = {
  -- Editor/UI
  Normal           = {fg = p.fg, bg = p.bg0},
  Terminal         = {fg = p.fg, bg = p.bg0},
  NormalFloat      = {fg = p.fg, bg = p.bg1},
  FloatBorder      = {fg = p.grey, bg = p.bg1},
  FloatTitle       = {fg = p.blue, bg = p.bg1, bold = true},
  FloatFooter      = {fg = p.grey, bg = p.bg1},
  Cursor           = {reverse = true},
  vCursor          = {link = 'Cursor'},
  iCursor          = {link = 'Cursor'},
  lCursor          = {link = 'Cursor'},
  CursorIM         = {reverse = true},
  CursorLine       = {bg = p.bg1},
  CursorColumn     = {bg = p.bg1},
  CursorLineNr     = {fg = p.fg},
  LineNr           = {fg = p.grey},
  SignColumn       = {fg = p.fg, bg = p.bg0},
  ToolbarLine      = {fg = p.fg},
  ToolbarButton    = {fg = p.bg0, bg = p.bg_blue},
  WinSeparator     = {fg = p.bg3},
  Visual           = {bg = p.bg3},
  VisualNOS        = {bg = p.bg2, underline = true},
  Search           = {fg = p.bg0, bg = p.bg_yellow},
  IncSearch        = {fg = p.bg0, bg = p.orange},
  CurSearch        = {fg = p.bg0, bg = p.orange},
  Substitute       = {fg = p.bg0, bg = p.green},
  MatchParen       = {bg = p.bg3},
  Pmenu            = {fg = p.fg, bg = p.bg1},
  PmenuSel         = {fg = p.bg0, bg = p.bg_blue},
  PmenuSbar        = {bg = p.bg1},
  PmenuThumb       = {bg = p.grey},
  StatusLine       = {fg = p.fg, bg = p.bg2},
  StatusLineTerm   = {fg = p.fg, bg = p.bg2},
  StatusLineNC     = {fg = p.grey, bg = p.bg1},
  StatusLineTermNC = {fg = p.grey, bg = p.bg1},
  TabLine          = {fg = p.fg, bg = p.bg1},
  TabLineFill      = {fg = p.grey, bg = p.bg1},
  TabLineSel       = {fg = p.bg0, bg = p.fg},
  WinBar           = {fg = p.fg, bg = p.bg0},
  WinBarNC         = {fg = p.grey, bg = p.bg0},
  WildMenu         = {fg = p.bg0, bg = p.blue},
  Folded           = {fg = p.fg, bg = p.bg1},
  FoldColumn       = {fg = p.fg, bg = p.bg1},
  DiffAdd          = {bg = p.diff_add},
  DiffChange       = {bg = p.diff_change},
  DiffDelete       = {bg = p.diff_delete},
  DiffText         = {bg = p.diff_text},
  DiffAdded        = {fg = p.green},
  DiffChanged      = {fg = p.blue},
  DiffRemoved      = {fg = p.red},
  DiffDeleted      = {link = 'DiffRemoved'},
  DiffFile         = {fg = p.cyan},
  DiffIndexLine    = {fg = p.grey},
  SpellBad         = {sp = p.red, undercurl = true},
  SpellCap         = {sp = p.yellow, undercurl = true},
  SpellLocal       = {sp = p.blue, undercurl = true},
  SpellRare        = {sp = p.purple, undercurl = true},
  NonText          = {fg = p.grey},
  Whitespace       = {fg = p.grey},
  SpecialKey       = {fg = p.grey},
  Directory        = {fg = p.blue},
  ErrorMsg         = {fg = p.red, bold = true},
  WarningMsg       = {fg = p.yellow, bold = true},
  MoreMsg          = {fg = p.blue, bold = true},
  ModeMsg          = {fg = p.fg, bold = true},
  Question         = {fg = p.yellow},
  QuickFixLine     = {fg = p.blue, underline = true},
  Debug            = {fg = p.yellow},
  debugPC          = {fg = p.bg0, bg = p.green},
  debugBreakpoint  = {fg = p.bg0, bg = p.red},
  ColorColumn      = {bg = p.bg1},
  Conceal          = {fg = p.grey, bg = p.bg1},
  SnippetTabstop   = {bg = p.bg2},
  EndOfBuffer      = {fg = p.bg0},
  Added            = {fg = p.green},
  Changed          = {fg = p.blue},
  Removed          = {fg = p.red},

  -- Syntax
  Comment        = {fg = p.grey, italic = true},
  Constant       = {fg = p.cyan},
  String         = {fg = p.green},
  Character      = {fg = p.orange},
  Number         = {fg = p.orange},
  Boolean        = {fg = p.orange},
  Float          = {fg = p.orange},
  Identifier     = {fg = p.red},
  Function       = {fg = p.blue},
  Statement      = {fg = p.purple},
  Conditional    = {fg = p.purple},
  Repeat         = {fg = p.purple},
  Label          = {fg = p.purple},
  Operator       = {fg = p.purple},
  Keyword        = {fg = p.purple},
  Exception      = {fg = p.purple},
  PreProc        = {fg = p.purple},
  Include        = {fg = p.purple},
  Define         = {fg = p.purple},
  Macro          = {fg = p.red},
  PreCondit      = {fg = p.purple},
  Type           = {fg = p.yellow},
  StorageClass   = {fg = p.yellow},
  Structure      = {fg = p.yellow},
  Typedef        = {fg = p.yellow},
  Special        = {fg = p.red},
  SpecialChar    = {fg = p.red},
  Tag            = {fg = p.green},
  Delimiter      = {fg = p.light_grey},
  SpecialComment = {fg = p.grey, italic = true},
  Todo           = {fg = p.red, italic = true},
  Title          = {fg = p.cyan},
  Underlined     = {underline = true},
  Ignore         = {fg = p.grey},
  Error          = {fg = p.red},

  -- Treesitter
  ['@attribute']                  = {fg = p.cyan},
  ['@attribute.builtin']          = {fg = p.blue},
  ['@boolean']                    = {fg = p.orange},
  ['@character']                  = {fg = p.orange},
  ['@character.special']          = {fg = p.red},
  ['@number']                     = {fg = p.orange},
  ['@number.float']               = {fg = p.orange},
  ['@comment']                    = {fg = p.grey, italic = true},
  ['@comment.error']              = {fg = p.red, italic = true},
  ['@comment.warning']            = {fg = p.yellow, italic = true},
  ['@comment.todo']               = {fg = p.purple, italic = true},
  ['@comment.note']               = {fg = p.blue, italic = true},
  ['@constant']                   = {fg = p.orange},
  ['@constant.builtin']           = {fg = p.orange},
  ['@constant.macro']             = {fg = p.orange},
  ['@constructor']                = {fg = p.yellow, bold = true},
  ['@diff.plus']                  = {fg = p.green},
  ['@diff.minus']                 = {fg = p.red},
  ['@diff.delta']                 = {fg = p.blue},
  ['@function']                   = {fg = p.blue},
  ['@function.builtin']           = {fg = p.cyan},
  ['@function.macro']             = {fg = p.cyan},
  ['@keyword']                    = {fg = p.purple},
  ['@keyword.debug']              = {fg = p.red},
  ['@label']                      = {fg = p.red},
  ['@module']                     = {fg = p.yellow},
  ['@module.builtin']             = {fg = p.orange},
  ['@none']                       = {},
  ['@operator']                   = {fg = p.fg},
  ['@property']                   = {fg = p.cyan},
  ['@punctuation.delimiter']      = {fg = p.light_grey},
  ['@punctuation.bracket']        = {fg = p.light_grey},
  ['@punctuation.special']        = {fg = p.red},
  ['@string']                     = {fg = p.green},
  ['@string.regexp']              = {fg = p.orange},
  ['@string.escape']              = {fg = p.red},
  ['@string.special']             = {fg = p.dark_cyan},
  ['@string.special.symbol']      = {fg = p.cyan},
  ['@string.special.url']         = {fg = p.cyan, underline = true},
  ['@string.special.path']        = {fg = p.green},
  ['@markup.strong']              = {fg = p.fg, bold = true},
  ['@markup.italic']              = {fg = p.fg, italic = true},
  ['@markup.strikethrough']       = {fg = p.fg, strikethrough = true},
  ['@markup.underline']           = {fg = p.fg, underline = true},
  ['@markup.heading']             = {fg = p.orange, bold = true},
  ['@markup.heading.1']           = {fg = p.red, bold = true},
  ['@markup.heading.2']           = {fg = p.purple, bold = true},
  ['@markup.heading.3']           = {fg = p.orange, bold = true},
  ['@markup.heading.4']           = {fg = p.red, bold = true},
  ['@markup.heading.5']           = {fg = p.purple, bold = true},
  ['@markup.heading.6']           = {fg = p.orange, bold = true},
  ['@markup.quote']               = {fg = p.grey, italic = true},
  ['@markup.math']                = {fg = p.fg},
  ['@markup.link']                = {fg = p.blue},
  ['@markup.link.label']          = {fg = p.cyan},
  ['@markup.link.url']            = {fg = p.cyan, underline = true},
  ['@markup.raw']                 = {fg = p.green},
  ['@markup.raw.block']           = {fg = p.green},
  ['@markup.list']                = {fg = p.red},
  ['@markup.list.checked']        = {fg = p.green, italic = true},
  ['@markup.list.unchecked']      = {fg = p.red, italic = true},
  ['@tag']                        = {fg = p.purple},
  ['@tag.attribute']              = {fg = p.yellow},
  ['@tag.delimiter']              = {fg = p.purple},
  ['@type']                       = {fg = p.yellow},
  ['@type.builtin']               = {fg = p.orange},
  ['@variable']                   = {fg = p.fg},
  ['@variable.builtin']           = {fg = p.red},
  ['@variable.parameter']         = {fg = p.red},
  ['@variable.parameter.builtin'] = {fg = p.orange},
  ['@variable.member']            = {fg = p.cyan},

  -- Diagnostics
  DiagnosticError            = {fg = p.red},
  DiagnosticWarn             = {fg = p.yellow},
  DiagnosticInfo             = {fg = p.cyan},
  DiagnosticHint             = {fg = p.purple},
  DiagnosticOk               = {fg = p.green},
  DiagnosticUnnecessary      = {fg = p.grey},
  DiagnosticDeprecated       = {fg = p.orange, strikethrough = true},
  DiagnosticVirtualTextError = {fg = p.dark_red},
  DiagnosticVirtualTextWarn  = {fg = p.dark_yellow},
  DiagnosticVirtualTextInfo  = {fg = p.dark_cyan},
  DiagnosticVirtualTextHint  = {fg = p.dark_purple},
  DiagnosticUnderlineError   = {sp = p.red, undercurl = true},
  DiagnosticUnderlineWarn    = {sp = p.yellow, undercurl = true},
  DiagnosticUnderlineInfo    = {sp = p.blue, undercurl = true},
  DiagnosticUnderlineHint    = {sp = p.purple, undercurl = true},
  DiagnosticUnderlineOk      = {sp = p.green, undercurl = true},
  DiagnosticSignError        = {fg = p.red},
  DiagnosticSignWarn         = {fg = p.yellow},
  DiagnosticSignInfo         = {fg = p.cyan},
  DiagnosticSignHint         = {fg = p.purple},
  DiagnosticSignOk           = {fg = p.green},
  DiagnosticFloatingError    = {link = 'DiagnosticError'},
  DiagnosticFloatingWarn     = {link = 'DiagnosticWarn'},
  DiagnosticFloatingInfo     = {link = 'DiagnosticInfo'},
  DiagnosticFloatingHint     = {link = 'DiagnosticHint'},
  DiagnosticFloatingOk       = {link = 'DiagnosticOk'},

  -- LSP
  LspReferenceText                         = {bg = p.bg2},
  LspReferenceRead                         = {bg = p.bg2},
  LspReferenceWrite                        = {bg = p.bg2},
  LspCodeLens                              = {fg = p.grey, italic = true},
  LspCodeLensSeparator                     = {fg = p.grey},
  LspInlayHint                             = {fg = p.grey, italic = true},
  LspSignatureActiveParameter              = {underline = true},
  ['@lsp.type.comment']                    = {link = '@comment'},
  ['@lsp.type.enum']                       = {link = '@type'},
  ['@lsp.type.enumMember']                 = {link = '@constant.builtin'},
  ['@lsp.type.interface']                  = {link = '@type'},
  ['@lsp.type.typeParameter']              = {link = '@type'},
  ['@lsp.type.keyword']                    = {link = '@keyword'},
  ['@lsp.type.namespace']                  = {link = '@module'},
  ['@lsp.type.parameter']                  = {link = '@variable.parameter'},
  ['@lsp.type.property']                   = {link = '@property'},
  ['@lsp.type.variable']                   = {link = '@variable'},
  ['@lsp.type.macro']                      = {link = '@function.macro'},
  ['@lsp.type.method']                     = {link = '@function.method'},
  ['@lsp.type.number']                     = {link = '@number'},
  ['@lsp.type.generic']                    = {fg = p.fg},
  ['@lsp.type.builtinType']                = {link = '@type.builtin'},
  ['@lsp.typemod.method.defaultLibrary']   = {link = '@function.builtin'},
  ['@lsp.typemod.function.defaultLibrary'] = {link = '@function.builtin'},
  ['@lsp.typemod.operator.injected']       = {link = '@operator'},
  ['@lsp.typemod.string.injected']         = {link = '@string'},
  ['@lsp.typemod.variable.defaultLibrary'] = {link = '@variable.builtin'},
  ['@lsp.typemod.variable.injected']       = {link = '@variable'},
  ['@lsp.typemod.variable.static']         = {link = '@constant'},

  -- mini.nvim
  MiniStatuslineModeNormal      = {fg = p.bg0, bg = p.blue, bold = true},
  MiniStatuslineModeInsert      = {fg = p.bg0, bg = p.green, bold = true},
  MiniStatuslineModeVisual      = {fg = p.bg0, bg = p.purple, bold = true},
  MiniStatuslineModeReplace     = {fg = p.bg0, bg = p.red, bold = true},
  MiniStatuslineModeCommand     = {fg = p.bg0, bg = p.yellow, bold = true},
  MiniStatuslineModeOther       = {fg = p.bg0, bg = p.cyan, bold = true},
  MiniStatuslineDevinfo         = {fg = p.fg, bg = p.bg2},
  MiniStatuslineFilename        = {fg = p.grey, bg = p.bg1},
  MiniStatuslineFileinfo        = {fg = p.fg, bg = p.bg2},
  MiniStatuslineInactive        = {fg = p.grey, bg = p.bg1},
  MiniTablineCurrent            = {fg = p.fg, bg = p.bg0, bold = true},
  MiniTablineVisible            = {fg = p.light_grey, bg = p.bg1},
  MiniTablineHidden             = {fg = p.grey, bg = p.bg_d},
  MiniTablineModifiedCurrent    = {fg = p.blue, bg = p.bg0, bold = true},
  MiniTablineModifiedVisible    = {fg = p.blue, bg = p.bg1},
  MiniTablineModifiedHidden     = {fg = p.blue, bg = p.bg_d},
  MiniTablineFill               = {bg = p.bg_d},
  MiniTablineTabpagesection     = {fg = p.bg0, bg = p.blue, bold = true},
  MiniCursorword                = {underline = true},
  MiniCursorwordCurrent         = {underline = true},
  MiniIndentscopeSymbol         = {fg = p.blue},
  MiniSurround                  = {fg = p.bg0, bg = p.orange},
  MiniNotifyBorder              = {link = 'FloatBorder'},
  MiniNotifyNormal              = {link = 'NormalFloat'},
  MiniNotifyTitle               = {fg = p.blue, bold = true},
  MiniTrailspace                = {bg = p.red},
  MiniHipatternsFixme           = {fg = p.bg0, bg = p.red, bold = true},
  MiniHipatternsHack            = {fg = p.bg0, bg = p.yellow, bold = true},
  MiniHipatternsTodo            = {fg = p.bg0, bg = p.blue, bold = true},
  MiniHipatternsNote            = {fg = p.bg0, bg = p.cyan, bold = true},
  MiniStarterCurrent            = {underline = true},
  MiniStarterFooter             = {fg = p.grey, italic = true},
  MiniStarterHeader             = {fg = p.blue},
  MiniStarterInactive           = {fg = p.grey},
  MiniStarterItem               = {fg = p.fg},
  MiniStarterItemBullet         = {fg = p.blue},
  MiniStarterItemPrefix         = {fg = p.yellow},
  MiniStarterSection            = {fg = p.purple, bold = true},
  MiniStarterQuery              = {fg = p.green, bold = true},
  MiniPickBorder                = {link = 'FloatBorder'},
  MiniPickBorderBusy            = {fg = p.yellow, bg = p.bg_d},
  MiniPickBorderText            = {fg = p.blue, bg = p.bg_d},
  MiniPickCursor                = {blend = 100},
  MiniPickHeader                = {fg = p.yellow, bold = true},
  MiniPickMatchCurrent          = {bg = p.bg2},
  MiniPickMatchMarked           = {fg = p.blue, bold = true},
  MiniPickMatchRanges           = {fg = p.green, bold = true},
  MiniPickNormal                = {link = 'NormalFloat'},
  MiniPickPreviewLine           = {bg = p.bg2},
  MiniPickPreviewRegion         = {link = 'Visual'},
  MiniPickPrompt                = {fg = p.blue, bg = p.bg_d},
  MiniFilesBorder               = {link = 'FloatBorder'},
  MiniFilesBorderModified       = {fg = p.yellow, bg = p.bg_d},
  MiniFilesCursorLine           = {bg = p.bg2},
  MiniFilesDirectory            = {link = 'Directory'},
  MiniFilesFile                 = {fg = p.fg},
  MiniFilesNormal               = {link = 'NormalFloat'},
  MiniFilesTitle                = {fg = p.blue, bg = p.bg_d, bold = true},
  MiniFilesTitleFocused         = {fg = p.orange, bg = p.bg_d, bold = true},
  MiniClueBorder                = {link = 'FloatBorder'},
  MiniClueDescGroup             = {fg = p.purple},
  MiniClueDescSingle            = {fg = p.fg},
  MiniClueNextKey               = {fg = p.blue, bold = true},
  MiniClueNextKeyWithPostkeys   = {fg = p.yellow, bold = true},
  MiniClueSeparator             = {fg = p.grey},
  MiniClueTitle                 = {fg = p.blue, bold = true},
  MiniDiffSignAdd               = {fg = p.green},
  MiniDiffSignChange            = {fg = p.blue},
  MiniDiffSignDelete            = {fg = p.red},
  MiniDiffOverAdd               = {link = 'DiffAdd'},
  MiniDiffOverChange            = {link = 'DiffText'},
  MiniDiffOverChangeBuf         = {link = 'DiffChange'},
  MiniDiffOverContext           = {link = 'DiffChange'},
  MiniDiffOverContextBuf        = {},
  MiniDiffOverDelete            = {link = 'DiffDelete'},
  MiniCompletionActiveParameter = {underline = true},
  MiniJump                      = {fg = p.bg0, bg = p.orange},
  MiniOperatorsExchangeFrom     = {bg = p.bg3},
  MiniAnimateCursor             = {reverse = true},
  MiniMapNormal                 = {link = 'NormalFloat'},
  MiniMapSymbolCount            = {fg = p.purple},
  MiniMapSymbolLine             = {fg = p.blue},
  MiniMapSymbolView             = {fg = p.grey},
  MiniDepsChangeAdded           = {fg = p.green},
  MiniDepsChangeRemoved         = {fg = p.red},
  MiniDepsHint                  = {link = 'DiagnosticHint'},
  MiniDepsInfo                  = {link = 'DiagnosticInfo'},
  MiniDepsMsgBreaking           = {fg = p.red, bold = true},
  MiniDepsPlaceholder           = {fg = p.grey},
  MiniDepsTitle                 = {fg = p.blue, bold = true},
  MiniDepsTitleError            = {fg = p.bg0, bg = p.red, bold = true},
  MiniDepsTitleSame             = {fg = p.grey},
  MiniDepsTitleUpdate           = {fg = p.bg0, bg = p.green, bold = true},
}

vim.cmd('highlight clear')
for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

vim.g.terminal_color_0  = p.black
vim.g.terminal_color_1  = p.red
vim.g.terminal_color_2  = p.green
vim.g.terminal_color_3  = p.yellow
vim.g.terminal_color_4  = p.blue
vim.g.terminal_color_5  = p.purple
vim.g.terminal_color_6  = p.cyan
vim.g.terminal_color_7  = p.fg
vim.g.terminal_color_8  = p.grey
vim.g.terminal_color_9  = p.red
vim.g.terminal_color_10 = p.green
vim.g.terminal_color_11 = p.yellow
vim.g.terminal_color_12 = p.blue
vim.g.terminal_color_13 = p.purple
vim.g.terminal_color_14 = p.cyan
vim.g.terminal_color_15 = p.fg

return p