#!/bin/bash

# System
alias df='df -Th --total'
alias du='du -ch'
alias dua='du -a --max-depth=1 | sort -hr'
alias free='free -ht'
alias grep='grep --color=auto'
alias ls='ls -F --color=auto --group-directories-first'
alias ll='ls -lAh'
alias mkd='mkdir -pv'
alias psa='ps -e -o pid,euser,pcpu,pmem,command'
alias pwo='poweroff'
alias rm='rm --preserve-root -I'
alias tree='tree -F -C --dirsfirst'

# Development
alias e="$EDITOR"
alias py='python3'

# Network
alias ip='ip -c -h'
alias ipa='ip -br address'
alias ipl='ip -br link'
alias ssp='ss -lnptu'

# Shortcuts
alias dl="cd $HOME/Downloads && ls"
alias doc="cd $HOME/Documents && ls"
alias tmp="cd $HOME/.tmp && ls"
[[ -n $WSL_HOME ]] && alias wh="cd $WSL_HOME && ls"
[[ -n $WSL_HOME ]] && alias wdl="cd $WSL_HOME/Downloads && ls"
[[ -n $WSL_HOME ]] && alias wdoc="cd $WSL_HOME/Documents && ls"
