#!/bin/bash

# Update and upgrade packages
function apt-update() {
  sudo apt update
  sudo apt -y upgrade
}

# Clean packages
function apt-clean() {
  sudo apt -y autoremove
}

# List intentionally installed packages
function apt-list() {
  (zcat "$(ls -tr /var/log/apt/history.log*.gz)"; cat /var/log/apt/history.log) 2> /dev/null |
  grep -E '^Commandline' |
  sed -e 's/Commandline: \(.*\)/\1/' |
  grep -E -v '^/usr/bin/unattended-upgrade'
}

# Delete swap files
function rm-swap() {
  rm -fv "$PWD"/*.swp
  rm -fv "$HOME"/.local/share/nvim/swap/*.swp
}

# Go back up N directories
function up() {
  if [[ $# -eq 0 ]]; then
    cd "../"
  elif [[ $# -eq 1 ]] && [[ $1 -gt 0 ]]; then
    local up_dir=""
    for _ in $(seq 1 "$1"); do
      up_dir+="../"
    done
    cd "$up_dir" || return 1
  else
    echo "Usage: up [n]"
  fi
}

# Pretty diff
function pdiff() {
  if [[ $# -ne 2 ]]; then
    echo "Usage: pdiff <source> <dest>"
  fi

  if [[ -x $(command -v delta) ]]; then
    delta "$1" "$2"
  else
    diff -s -u --color=always "$1" "$2"
  fi
}

# Print command cheatsheet
function cheat() {
  curl -fsSL "cheat.sh/$1"
}

# Browse git commits
function glog() {
  local log_fmt="%C(yellow)%h%Cred%d %Creset%s %Cgreen(%ar)%Creset"
  local commit_hash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
  local view_commit="$commit_hash | xargs -I hash sh -c \"git i --color=always hash | delta\""

  git log --color=always --format="$log_fmt" "$@" | \
    fzf --no-sort --tiebreak=index --no-multi --reverse --ansi \
    --header="enter to view, alt-y to copy hash" --preview="$view_commit" \
    --bind="enter:execute:$view_commit | less -R" \
    --bind="alt-y:execute:$commit_hash | xclip -selection clipboard"
}
