#!/bin/bash

# Get current git status
function parse_git_status {
  local status=$(git status 2> /dev/null)
  local bits=""

  if [[ "$status" == *"Your branch is ahead"* ]]; then
    bits+=">"
  elif [[ "$status" == *"Your branch is behind"* ]]; then
    bits+="<"
  fi
  if [[ "$status" == *"Changes to be committed"* ]]; then
    bits+="="
  fi
  if [[ "$status" == *"Changes not staged for commit"* ]]; then
    bits+="~"
  fi
  if [[ "$status" == *"Untracked files"* ]]; then
    bits+="?"
  fi
  if [[ "$status" == *"Unmerged paths"* ]]; then
    bits+="!"
  fi

  if [[ -n "$bits" ]]; then
    echo " $bits"
  else
    echo ""
  fi
}

# Get current git branch and status
function parse_git() {
  local br=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
  local st=""

  if [[ -n "$br" ]]; then
    st=$(parse_git_status)
    echo " [$br$st]"
  else
    echo ""
  fi
}
